#htmx.enabled=true
#server.port=8080

spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    jpa:
      database: ${JPA_DATABASE}
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
      show-sql: true